In [3]:
import pandas as pd
import numpy as np

#fonction sous Python qui permet de calculer la matrice de confusion à partir de deux vecteurs 𝑦 et y_estime
def confusion_matrix(actual, predicted):
    classes       = np.unique(np.concatenate((actual,predicted)))
    confusion_mtx = np.empty((len(classes),len(classes)))
    for i,a in enumerate(classes):
        for j,p in enumerate(classes):
            confusion_mtx[i,j] = np.where((actual==a)*(predicted==p))[0].shape[0]
    return confusion_mtx


#2 une fonction qui calcule la précision par classe.
def precision_par_classe(matrice_conf):
    pre=[]
    for i in range(len(matrice_conf)):
        for j in range(len(matrice_conf)):
            if i == j:
                som_colone_predi = np.sum(matrice_conf[:,j])
                prediction = matrice_conf[i,j]/som_colone_predi
                pre.append(prediction)
    return pre

#2 une fonction qui calcule la précision globale.
def precision_globale(matrice_conf):
    pre_classe = precision_par_classe(matrice_conf)
    pre_globale = sum(pre_classe)/len(pre_classe)
    return pre_globale
    

#3 une fonction qui permet de calculer le rappel par classe
def rappel_par_classe(matrice_conf):
    rappel_list=[]
    for i in range(len(matrice_conf)):
        for j in range(len(matrice_conf)):
            if i == j:
                som_ligne_actu = np.sum(matrice_conf[j,:])
                rappel = matrice_conf[i,j]/som_ligne_actu
                rappel_list.append(rappel)
    return rappel_list

#3 une fonction qui permet de calculer le rappel globale
def rappel_globale(matrice_conf):
    rap_classe = rappel_par_classe(matrice_conf)
    rap_globale = sum(rap_classe)/len(rap_classe)
    return rap_globale
    
#4 une fonction pour calculer la F-mesure globale.
def f_mesure_globale(matrice_conf):
    precision = precision_globale(matrice_conf)
    rappel = rappel_globale(matrice_conf)
    return 2 * ((precision * rappel)/ (precision + rappel))


#4 une fonction pour calculer la F-mesure par classe.    
def f_mesure_classe(matrice_conf):
    precision_classe = precision_par_classe(matrice_conf)
    rappel_classe = rappel_par_classe(matrice_conf)
    f_mesure = []
    for j in range(len(precision_classe)):
        f_mesure.append(2*((precision_classe[j]*rappel_classe[j])/(precision_classe[j]+rappel_classe[j])))
    return f_mesure


    
    
#lire fichier TP1.xlsx
df = pd.read_excel('TP1.xlsx')
y = list(df['y'])
y_estime = list(df['y_estimé'])

#confusion matrix
matrice_conf = confusion_matrix(y, y_estime)
print("Matrice de confusion :")
print(matrice_conf, '\n')

#precision par classe
pre_classe=precision_par_classe(matrice_conf)
print("Precision par classe :")
print(pre_classe, '\n')

#precision globale
pre_globale=precision_globale(matrice_conf)
print("Precision globale :")
print(pre_globale, '\n')


#rappel par classe
rapl_classe=rappel_par_classe(matrice_conf)
print("Rappel par classe :")
print(rapl_classe, '\n')

#rappel globale
rapl_globale=rappel_globale(matrice_conf)
print("Rappel globale :")
print(rapl_globale, '\n')


#f-mesure globale
f_mesure_globale = f_mesure_globale(matrice_conf)
print("F-mesure globale :")
print(f_mesure_globale, '\n')

#f-mesure par classe
f_mesure_cl= f_mesure_classe(matrice_conf)
print("F-mesure par classe :")
print(f_mesure_cl, '\n')




Matrice de confusion :
[[24.  0.  0.]
 [ 0. 26.  0.]
 [ 0.  1. 24.]] 

Precision par classe :
[1.0, 0.9629629629629629, 1.0] 

Precision globale :
0.9876543209876543 

Rappel par classe :
[1.0, 1.0, 0.96] 

Rappel globale :
0.9866666666666667 

F-mesure globale :
0.9871602467900616 

F-mesure par classe :
[1.0, 0.9811320754716981, 0.9795918367346939] 

